# Spring Application Name
spring.application.name=restaurant_inventory_management_system

# Oracle Database Connection Settings
spring.datasource.url=jdbc:oracle:thin:@fsktmdbora.upm.edu.my:1521:FSKTM
spring.datasource.username=G229259
spring.datasource.password=229259
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Thymeleaf Cache config (disable for easy development updates)
spring.thymeleaf.cache=false